routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('forget-password', 'App\Http\Controllers\Auth\ForgotPasswordController@getEmail')->name('password.request');
// Route::post('forget-password', 'App\Http\Controllers\Auth\ForgotPasswordController@postEmail')->name('password.email');

// Route::get('reset-password/', 'App\Http\Controllers\Auth\ResetPasswordController@getPassword')->name('resetPass');
// Route::post('update-password/', 'App\Http\Controllers\Auth\ResetPasswordController@updatePassword');


Route::prefix('admin')->group(function () {
    Route::get('/', [App\Http\Controllers\AdminController::class, 'index'])->name('admin');
    Route::get('users', [App\Http\Controllers\AdminController::class, 'getusers'])->name('getusers');
    Route::get('vidoes', [App\Http\Controllers\AdminController::class, 'getvideos'])->name('getvideos');
    Route::get('comments', [App\Http\Controllers\AdminController::class, 'getcomments'])->name('getcomments');
    Route::post('changeuserstatus', [App\Http\Controllers\AdminController::class, 'changeuserStatus'])->name('changeUserStatus');
    Route::post('changecommentstatus', [App\Http\Controllers\AdminController::class, 'changeCommentStatus'])->name('changeCommentStatus');
    Route::post('changevideostatus', [App\Http\Controllers\AdminController::class, 'changevideoStatus'])->name('changeVideoStatus');
    Route::get('video/{id}', [App\Http\Controllers\AdminController::class, 'videoDetails'])->name('videoDetails');
});


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

app/Http/Controllers/AdminController.php
<?php

namespace App\Http\Controllers;
use App\Models\User;
use App\Models\Video;
use App\Models\Comment;
use App\Models\ReportVideo;
use App\Utils\AppConstant;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;

class AdminController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth.admin');
    }
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function adminLoginForm()
    {
        // dd("hello");
        return view('admin.adminlogin');
    }

    public function index()
    {
        return view('admin.adminDashboard');
    }

    public function getusers(Request $request)
    {
        if ($request->ajax()) {
            $users = User::query();
            return Datatables::of($users)
            ->addColumn('action', function(User $user) {
                if($user->status == 1)
                {
                    return '<button type="button" class="btn btn-secondary m-0" onclick="UserSwal(\''.$user->id.'\') ">Deactivate</button>';
                }
                else{
                    return '<button type="button" class="btn btn-secondary m-0" onclick="UserSwal(\''.$user->id.'\') ">Activate</button>';
                }
            })
            ->make(true);
        }
        return view('admin.userdetails');

    }

    public function getvideos(Request $request)
    {
        if ($request->ajax()) {
            $videos = Video::query();
            return Datatables::of($videos)
            ->addColumn('action', '<a class="btn btn-secondary btn-sm pr-4" href="{{route(\'videoDetails\',$id )}}" role="button"><i class="fas fa-video"></i> View Details</a>')
            ->make(true);
        }
        return view('admin.allvideos');
    }

    public function getcomments(Request $request)
    {
        if ($request->ajax()) {
            $comments = Comment::query();
            return Datatables::of($comments)
            ->addColumn('action', function(Comment $comment) {
                if($comment->status == 1)
                {
                    return '<button type="button" class="btn btn-secondary m-0" onclick="CommentSwal(\''.$comment->id.'\') ">Deactivate</button>';
                }
                else{
                    return '<button type="button" class="btn btn-secondary m-0" onclick="CommentSwal(\''.$comment->id.'\') ">Activate</button>';
                }
            })
            ->make(true);
        }
        return view('admin.allcomments');

        $comments = Comment::all();
        return view('admin.allcomments',compact('comments'));
    }

    public function videoDetails($id)
    {
        $reported = Video::withCount(['vote'  => function($query){
            $query->where('status',1);
        },'comments'  => function($query){
            $query->where('status',1);
        }])->with(['reports' => function($query){
            $query->where('status', AppConstant::STATUS_INACTIVE );
        }])->where( 'id', $id )->first();

        return view('admin.videodetails',compact('reported'));
    }
    
    public function changeuserStatus(Request $request)
    {
        $user = User::findOrFail($request->id);

        $user->status = !$user->status;
        $user->save();

    }

    public function changeVideoStatus(Request $request)
    {
        $video = Video::findOrFail($request->id);
        $video->status = !$video->status;
        $video->save();
        return $video;
        // return \redirect()->back();
    }
    
    public function changeCommentStatus(Request $request)
    {
        $comment = Comment::findOrFail($request->id);
        $comment->status = !$comment->status;
        $comment->save();
        // dd("hello");
        // return redirect()->back();
    }
}

app/Http/Controllers/VideoApiController.php
<?php

namespace App\Http\Controllers;
use TymonJWTAuthExceptionsJWTException;
use Hash;
use Validator;
use JWTAuth;
use DB;

use App\Models\User;
use App\Models\Video;
use App\Models\VoteCount;
use App\Models\Comment;
use App\Models\ReportComment;
use App\Models\ReportVideo;

use App\Traits\ApiResponse;
use App\Utils\AppConstant;
use App\Jobs\SendVerifyEmail;

use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response; 
use Carbon\Carbon;


class VideoApiController extends Controller
{
    use ApiResponse;

    public function FileUpload(Request $request)
    {
        try {
            // $validated = $request->validated();

            $token = str_replace('Bearer ', '', $request->header('Authorization'));

            $token_data = JWTAuth::getPayload($token)->toArray();
            $u_id = $token_data['id'];
            
            $user = User::find($u_id);

            if(!$user){
                $this->setMeta('message', __('messages.user.notFound'));
                $this->setMeta('status', AppConstant::STATUS_FAIL);
                return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
            } 

            if($request->hasFile('url')){
                
                $file = $request->file('url');
                $file_name = $file->getClientOriginalName();
                $path = $request->file('url')->storeAs(
                    'public/videos',$file_name
                );
            }

            $video = new Video;
            $video->video_path = 'storage/videos/'.$file_name;
            $video->VideoName = $file_name;
            $video->user_id = $u_id;
    
            $video->save();
            
            $this->setMeta('message', __('messages.video.upload'));
            $this->setMeta('url', '/storage/videos/'.$file_name);
            $this->setMeta('status', AppConstant::STATUS_OK);

            return response()->json($this->setResponse(),AppConstant::OK);

        } catch (QueryException $e) {

            $this->setMeta('message', __('messages.somethingWrong'));
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }catch (\Exception $e) {

            $this->setMeta('message', $e->getMessage());
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);

        }
    }

    public function getUsersVideo(Request $request)
    { 
        try{
            $token = str_replace('Bearer ', '', $request->header('Authorization'));

            $token_data = JWTAuth::getPayload($token)->toArray();
            $u_id = $token_data['id'];

            $user_video = User::with(['video'  => function($query){
                $query->where('status',1);
            }])->where('id',$u_id)->get();

            $this->setData('User_Video', $user_video);
            $this->setData('status', AppConstant::STATUS_OK);
            return response()->json($this->setResponse(),AppConstant::OK);

        }catch (QueryException $e) {

            $this->setMeta('message', __('messages.somethingWrong'));
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }catch (\Exception $e) {

            $this->setMeta('message', $e->getMessage());
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }
    }

    public function getVideo(Request $request){
        try{
            $v_id = $request->video_id;

            $video = Video::with('author')->where(['id' => $v_id, 'status' => 1])->first();
            if(!$video){
                $this->setMeta('message', __('messages.video.notFound'));
                $this->setMeta('status', AppConstant::STATUS_FAIL);
                return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
            }
            $this->setData('Video', $video);
            $this->setData('status', AppConstant::STATUS_OK);
            return response()->json($this->setResponse(),AppConstant::OK);

        }catch (QueryException $e) {

            $this->setMeta('message', __('messages.somethingWrong'));
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }catch (\Exception $e) {

            $this->setMeta('message', $e->getMessage());
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }
    }

    public function getAllVideo()
    {
        try{
            $video = Video::with(['author','comments'  => function($query){
                $query->where('status',1);
            },'vote' => function($query){
                $query->where('vote',1);
            }])->withCount(['comments'  => function($query){
                $query->where('status',1);
            },'vote' => function($query){
                $query->where('vote',1);
            }])->where('status',1)->get();

            if(!$video){
                $this->setMeta('message', __('messages.video.notFound'));
                $this->setMeta('status', AppConstant::STATUS_FAIL);
                return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
            }

            $this->setMeta('message', __('messages.video.allVideos'));
            $this->setMeta('status', AppConstant::STATUS_OK);
            $this->setData('All Videos', $video);
            return response()->json($this->setResponse(),AppConstant::OK);

        }catch (QueryException $e) {

            $this->setMeta('message', __('messages.somethingWrong'));
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }catch (\Exception $e) {

            $this->setMeta('message', $e->getMessage());
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }

    }

    public function setLikes(Request $request)
    {
        try{
            $token = str_replace('Bearer ', '', $request->header('Authorization'));

            $token_data = JWTAuth::getPayload($token)->toArray();
            $u_id = $token_data['id'];

            $v_id = $request->video_id;
            $vote = $request->status;

            $video = Video::where(['id' => $v_id, 'status' => 1])->first();
            if(!$video){
                $this->setMeta('message', __('messages.video.notFound'));
                $this->setMeta('status', AppConstant::STATUS_FAIL);
                return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
            }

            $ex1 = VoteCount::updateOrCreate([
                'user_id' =>  $u_id,
                'video_id' => $v_id
            ],[
                'vote' => $vote
            ],
            );

            $this->setMeta('message', __('messages.voteSuccess'));
            $this->setMeta('status', AppConstant::STATUS_OK);
            return response()->json($this->setResponse(),AppConstant::OK);


        }catch (QueryException $e) {

            $this->setMeta('message', __('messages.somethingWrong'));
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }catch (\Exception $e) {

            $this->setMeta('message', $e->getMessage());
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }

    }

    public function getLikes(Request $request)
    {
        try{

            $v_id = $request->video_id;

            $video = Video::where(['id' => $v_id, 'status' => 1])->first();
            if(!$video){
                $this->setMeta('message', __('messages.video.notFound'));
                $this->setMeta('status', AppConstant::STATUS_FAIL);
                return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
            }

            $ex = Video::with(['vote' => function($query){
                $query->where('vote',1);
            }])->withCount(['vote' => function($query){
                $query->where('vote',1);
            }])->where('id', $v_id)->first();
        
            $this->setMeta('status', AppConstant::STATUS_OK);
            $this->setData('Video', $ex);
            return response()->json($this->setResponse(),AppConstant::OK);

        }catch (QueryException $e) {

            $this->setMeta('message', __('messages.somethingWrong'));
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }catch (\Exception $e) {

            $this->setMeta('message', $e->getMessage());
            $this->setMeta('status', AppConstant::STATUS_FAIL);
            return response()->json($this->setResponse(), AppConstant::INTERNAL_SERVER_ERROR);
        }
    }

    public function setComments(Request $request)
    {
        try{
            $token = str_replace('Bearer ', '', $request->header('Authorization'));

            $token_data = JWTAuth::getPayload($token)->toArray();
            $u_id = $token_data['id'];

            $v_id = $request->video_id;
            $comment = $request->comment;

            $video = Video::where(['id' => $v_id, 'status' => 1])->first();
            if(!$video){

resources/views/admin/adminDashboard.blade.php
@extends('layouts.admin')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Admin Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    Welcome {{$admin->name}}
                    
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/adminlogin.blade.php
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from demo.interface.club/limitless/demo/bs4/Template/layout_1/LTR/default/full/login_tabbed.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 29 Mar 2019 10:46:33 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<title>Limitless - Responsive Web Application Kit by Eugene Kopyov</title>

	<!-- Global stylesheets -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/icons/icomoon/styles.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/assets/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/assets/bootstrap_limitless.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/assets/layout.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/assets/components.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/assets/colors.min.css') }}" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->

	<!-- Core JS files -->
	<script src="{{ asset('js/main/jquery.min.js') }}"></script>
    <script src="{{ asset('js/main/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('js/plugins/loaders/blockui.min.js') }}"></script>

	<!-- Theme JS files -->
    <script src="{{ asset('js/demo_pages/login.js') }}"></script>
	<script src="{{ asset('js/plugins/forms/styling/uniform.min.js') }}"></script>
    <script src="{{ asset('js/assets/app.js') }}"></script>
	<!-- /theme JS files -->

</head>

<body>

	<!-- Page content -->
	<div class="page-content login-cover">

		<!-- Main content -->
		<div class="content-wrapper">

			<!-- Content area -->
			<div class="content d-flex justify-content-center align-items-center">

				<!-- Login form -->
				<form class="login-form wmin-sm-400" action="http://demo.interface.club/limitless/demo/bs4/Template/layout_1/LTR/default/full/index.html">
					<div class="card mb-0">
						<ul class="nav nav-tabs nav-justified alpha-grey mb-0">
							<li class="nav-item"><a href="#login-tab1" class="nav-link border-y-0 border-left-0 active" data-toggle="tab"><h6 class="my-1">Sign in</h6></a></li>
							<li class="nav-item"><a href="#login-tab2" class="nav-link border-y-0 border-right-0" data-toggle="tab"><h6 class="my-1">Register</h6></a></li>
						</ul>

						<div class="tab-content card-body">
							<div class="tab-pane fade show active" id="login-tab1">
								<div class="text-center mb-3">
									<i class="icon-reading icon-2x text-slate-300 border-slate-300 border-3 rounded-round p-3 mb-3 mt-1"></i>
									<h5 class="mb-0">Login to your account</h5>
									<span class="d-block text-muted">Your credentials</span>
								</div>

								<div class="form-group form-group-feedback form-group-feedback-left">
									<input type="text" class="form-control" placeholder="Username">
									<div class="form-control-feedback">
										<i class="icon-user text-muted"></i>
									</div>
								</div>

								<div class="form-group form-group-feedback form-group-feedback-left">
									<input type="password" class="form-control" placeholder="Password">
									<div class="form-control-feedback">
										<i class="icon-lock2 text-muted"></i>
									</div>
								</div>

								<div class="form-group d-flex align-items-center">
									<div class="form-check mb-0">
										<label class="form-check-label">
											<input type="checkbox" name="remember" class="form-input-styled" checked data-fouc>
											Remember
										</label>
									</div>

									<a href="login_password_recover.html" class="ml-auto">Forgot password?</a>
								</div>

								<div class="form-group">
									<button type="submit" class="btn btn-primary btn-block">Sign in</button>
								</div>

								<div class="form-group text-center text-muted content-divider">
									<span class="px-2">or sign in with</span>
								</div>

								<div class="form-group text-center">
									<button type="button" class="btn btn-outline bg-indigo border-indigo text-indigo btn-icon rounded-round border-2"><i class="icon-facebook"></i></button>
									<button type="button" class="btn btn-outline bg-pink-300 border-pink-300 text-pink-300 btn-icon rounded-round border-2 ml-2"><i class="icon-dribbble3"></i></button>
									<button type="button" class="btn btn-outline bg-slate-600 border-slate-600 text-slate-600 btn-icon rounded-round border-2 ml-2"><i class="icon-github"></i></button>
									<button type="button" class="btn btn-outline bg-info border-info text-info btn-icon rounded-round border-2 ml-2"><i class="icon-twitter"></i></button>
								</div>

								<div class="form-group text-center text-muted content-divider">
									<span class="px-2">Don't have an account?</span>
								</div>

								<div class="form-group">
									<a href="#" class="btn btn-light btn-block">Sign up</a>
								</div>

								<span class="form-text text-center text-muted">By continuing, you're confirming that you've read our <a href="#">Terms &amp; Conditions</a> and <a href="#">Cookie Policy</a></span>
							</div>

							<div class="tab-pane fade" id="login-tab2">
								<div class="text-center mb-3">
									<i class="icon-plus3 icon-2x text-success border-success border-3 rounded-round p-3 mb-3 mt-1"></i>
									<h5 class="mb-0">Create account</h5>
									<span class="d-block text-muted">All fields are required</span>
								</div>

								<div class="form-group form-group-feedback form-group-feedback-left">
									<input type="text" class="form-control" placeholder="Your username">
									<div class="form-control-feedback">
										<i class="icon-user-check text-muted"></i>
									</div>
								</div>

								<div class="form-group form-group-feedback form-group-feedback-left">
									<input type="password" class="form-control" placeholder="Your password">
									<div class="form-control-feedback">
										<i class="icon-user-lock text-muted"></i>
									</div>
								</div>

								<div class="form-group form-group-feedback form-group-feedback-left">
									<input type="password" class="form-control" placeholder="Your email">
									<div class="form-control-feedback">
										<i class="icon-mention text-muted"></i>
									</div>
								</div>

								<div class="form-group text-center text-muted content-divider">
									<span class="px-2">Additions</span>
								</div>

								<div class="form-group">
									<div class="form-check">
										<label class="form-check-label">
											<input type="checkbox" name="remember" class="form-input-styled" checked data-fouc>
											Send me <a href="#">test account settings</a>
										</label>
									</div>

									<div class="form-check">
										<label class="form-check-label">
											<input type="checkbox" name="remember" class="form-input-styled" checked data-fouc>
											Subscribe to monthly newsletter
										</label>
									</div>

									<div class="form-check">
										<label class="form-check-label">
											<input type="checkbox" name="remember" class="form-input-styled" data-fouc>
											Accept <a href="#">terms of service</a>
										</label>
									</div>
								</div>

								<button type="submit" class="btn bg-dark btn-block">Register</button>
							</div>
						</div>
					</div>
				</form>
				<!-- /login form -->

			</div>
			<!-- /content area -->

		</div>
		<!-- /main content -->

	</div>
	<!-- /page content -->

</body>

<!-- Mirrored from demo.interface.club/limitless/demo/bs4/Template/layout_1/LTR/default/full/login_tabbed.html by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 29 Mar 2019 10:46:33 GMT -->
</html>

resources/views/admin/videodetails.blade.php
@extends('layouts.admin')

@section('content')

           
    <!-- /basic datatable -->
    <div class="row justify-conetnt-center">
        <div class="card card1 col-md-12">
            <div class="card-header header-elements-inline">
                <h3 class="card-title fw-bold">Video Details</h3>
                <a class="btn btn-secondary ml-auto" href="{{route('getvideos')}}" role="button"><i class="fas fa-arrow-left"></i> Back</a></td>
            </div>
            
            <div class="row d-flex">
                <div class="col-md-4 img1">
                    <img src="../../storage/flat/13.png"  alt="...">
                </div>
                <div class="col-md-8 pt-0">
                    <div class="card-body">
                    <form>
                        <div class="form-group row">
                            <label for="Name" class="col-sm-2 text-dark col-form-label">Name: </label>
                            <div class="col-sm-10">
                                <p>{{$reported->VideoName}}</p>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="Path" class="col-sm-2 text-dark col-form-label">Path: </label>
                            <div class="col-sm-10">
                                <p>{{$reported->video_path}}</p>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="About" class="col-sm-2 text-dark col-form-label">About: </label>
                            <div class="col-sm-10">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</p>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="Likes" class="col-sm-2 text-dark col-form-label">Likes: </label>
                            <div class="col-sm-10">
                                <p>{{$reported->vote_count}}</p>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="Likes" class="col-sm-2 text-dark col-form-label">Comments: </label>
                            <div class="col-sm-10">
                                <p>{{$reported->comments_count}}</p>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="Status" class="col-sm-2 text-dark col-form-label">Status: </label>
                            <div class="col-sm-10">
                                <p>
                                @if($reported->status == 1)
                                    <span class="badge bg-success mr-5">Active</span>
                                    <button type="button" class="btn btn-secondary m-0 pr-4" onclick="VideoSwal('{{$reported->id}}')">Deactivate</button>
                                @else
                                    <span class="badge bg-danger mr-5">Reported</span>
                                    <button type="button" class="btn btn-secondary m-0 pr-4" onclick="VideoSwal('{{$reported->id}}')">Activate</button>
                                @endif
                                </p>
                            </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
    
    <div class="row">
        <div class="col-md-7">
            <div class="card border-light">
                <div class="card-header header-elements-inline p-0">
                    <h3 class="card-title fw-bold">Video Reported By:</h3>
                </div>
                <table class="table datatable-basic">
                    <thead class="bg-dark">
                        <tr>
                            <th>#</th>
                            <th>UserID</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $i=1; ?>
                        @foreach($reported->reports as $report)
                        <tr>
                            <td>{{ $i++ }}</td>
                            <td>{{ $report->user_id }}</td>
                            @if($report->status == 1)
                            <td><span class="badge bg-success">Active</span></td>
                            @else
                            <td><span class="badge bg-danger">Reported</span></td>
                            @endif
                        </tr>
                        @endforeach
                        
                    </tbody>
                </table>
            </div>
        </div>
        
    </div>
    <script type="text/javascript">
    function VideoSwal(id){
                swal({
                    title: "Are you sure?",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                if (willDelete) {
                    changeVideoStatus(id);
                } else {
                    swal("Video file is safe!");
                }
                });
            }
            function changeVideoStatus(id){
                $.ajax({
                    url: '{{route('changeVideoStatus')}}',
                    type: 'POST',
                    data : { 
                            "id": id,
                            "_token": "{{ csrf_token() }}", },
                    error: function() {
                        console.log('Something is wrong');
                    },
                    success: function(data) {
                        console.log(data.status);
                        if(data.status == true){
                            $(".badge.mr-5").addClass("bg-success").removeClass("bg-danger").text("Active");
                            $(".btn.btn-secondary.m-0.pr-4").text("Deactivate");
                        }
                        else{
                            $(".badge.mr-5").addClass("bg-danger").removeClass("bg-success").text("Reported");
                            $(".btn.btn-secondary.m-0.pr-4").text("Activate");
                        }
                    }
                });
            }
        </script>
@endsection